wget --output-document=2006nogales http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=nogales
wget --output-document=2011nogales http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=nogales
wget --output-document=2006douglas http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=douglas
wget --output-document=2011douglas http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=douglas
wget --output-document=2006phoenix http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=phoenix
wget --output-document=2011phoenix http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=phoenix
wget --output-document=2006tucson http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=tucson
wget --output-document=2011tucson http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=tucson
wget --output-document=2006denver http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=denver
wget --output-document=2011denver http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=denver
wget --output-document=2006yuma http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=yuma
wget --output-document=2011yuma http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=yuma
wget --output-document=2006calexico http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=calexico
wget --output-document=2011calexico http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=calexico
wget --output-document=2006san_diego http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=san_diego
wget --output-document=2011san_diego http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=san_diego
wget --output-document=2006santa_ana http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=santa_ana
wget --output-document=2011santa_ana http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=santa_ana
wget --output-document=2006san_bernardino http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=san_bernardino
wget --output-document=2011san_bernardino http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=san_bernardino
wget --output-document=2006los_angeles http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=los_angeles
wget --output-document=2011los_angeles http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=los_angeles
wget --output-document=2006oxnard http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=oxnard
wget --output-document=2011oxnard http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=oxnard
wget --output-document=2006san_jose http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=san_jose
wget --output-document=2011san_jose http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=san_jose
wget --output-document=2006fresno http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=fresno
wget --output-document=2011fresno http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=fresno
wget --output-document=2006sacramento http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=sacramento
wget --output-document=2011sacramento http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=sacramento
wget --output-document=2006las_vegas http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=las_vegas
wget --output-document=2011las_vegas http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=las_vegas
wget --output-document=2006san_francisco http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=san_francisco
wget --output-document=2011san_francisco http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=san_francisco
wget --output-document=2006el_paso http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=el_paso
wget --output-document=2011el_paso http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=el_paso
wget --output-document=2006albuquerque http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=albuquerque
wget --output-document=2011albuquerque http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=albuquerque
wget --output-document=2006presidio http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=presidio
wget --output-document=2011presidio http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=presidio
wget --output-document=2006del_rio http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=del_rio
wget --output-document=2011del_rio http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=del_rio
wget --output-document=2006eagle_pass http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=eagle_pass
wget --output-document=2011eagle_pass http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=eagle_pass
wget --output-document=2006laredo http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=laredo
wget --output-document=2011laredo http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=laredo
wget --output-document=2006san_antonio http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=san_antonio
wget --output-document=2011san_antonio http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=san_antonio
wget --output-document=2006austin http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=austin
wget --output-document=2011austin http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=austin
wget --output-document=2006houston http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=houston
wget --output-document=2011houston http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=houston
wget --output-document=2006dallas http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=dallas
wget --output-document=2011dallas http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=dallas
wget --output-document=2006mcallen http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=mcallen
wget --output-document=2011mcallen http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=mcallen
wget --output-document=2006brownsville http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=brownsville
wget --output-document=2011brownsville http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=brownsville
wget --output-document=2006kansas_city http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=kansas_city
wget --output-document=2011kansas_city http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=kansas_city
wget --output-document=2006orlando http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=orlando
wget --output-document=2011orlando http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=orlando
wget --output-document=2006miami http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=miami
wget --output-document=2011miami http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=miami
wget --output-document=2006raleigh http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=raleigh
wget --output-document=2011raleigh http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=raleigh
wget --output-document=2006atlanta http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=atlanta
wget --output-document=2011atlanta http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=atlanta
wget --output-document=2006indianapolis http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=indianapolis
wget --output-document=2011indianapolis http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=indianapolis
wget --output-document=2006washington http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=washington
wget --output-document=2011washington http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=washington
wget --output-document=2006philadelphia http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=philadelphia
wget --output-document=2011philadelphia http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=philadelphia
wget --output-document=2006new_york http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=new_york
wget --output-document=2011new_york http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=new_york
wget --output-document=2006boston http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=boston
wget --output-document=2011boston http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=boston
wget --output-document=2006detroit http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=detroit
wget --output-document=2011detroit http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=detroit
wget --output-document=2006chicago http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=chicago
wget --output-document=2011chicago http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=chicago
wget --output-document=2006omaha http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=omaha
wget --output-document=2011omaha http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=omaha
wget --output-document=2006saint_paul http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=saint_paul
wget --output-document=2011saint_paul http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=saint_paul
wget --output-document=2006salt_lake_city http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=salt_lake_city
wget --output-document=2011salt_lake_city http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=salt_lake_city
wget --output-document=2006portland http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=portland
wget --output-document=2011portland http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=portland
wget --output-document=2006seattle http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=seattle
wget --output-document=2011seattle http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=seattle
wget --output-document=2006anchorage http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=anchorage
wget --output-document=2011anchorage http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=anchorage
wget --output-document=2006nueva_orleans http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=nueva_orleans
wget --output-document=2011nueva_orleans http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=nueva_orleans
wget --output-document=2006little_rock http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=little_rock
wget --output-document=2011little_rock http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=little_rock
wget --output-document=2006boise http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2006\&consulado=boise
wget --output-document=2011boise http://univision.akorahq.com/ciudades_expulsoras/municipios_x_consulado.php?year=2011\&consulado=boise
